# Project on Tartu Smart Bike data analysis
## Introduction to Data Science - LTAT.02.002

## Data exploring
**Used data:**  Confidential Tartu Smart Bike rental and locations data (June 2019 - September 2019)

In [1]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
plt.style.use("ggplot")  # Default style

In [2]:
# reading in data from csv-s
data_routes_june = pd.read_csv("data_for_IDS2019_project_team_W17\\bicycle_data\\routes_201906.csv",sep=',')
data_routes_july = pd.read_csv("data_for_IDS2019_project_team_W17\\bicycle_data\\routes_201907.csv",sep=',')
data_routes_august = pd.read_csv("data_for_IDS2019_project_team_W17\\bicycle_data\\routes_201908.csv",sep=',')
data_routes_september = pd.read_csv("data_for_IDS2019_project_team_W17\\bicycle_data\\routes_201909.csv",sep=',')

### Performing the exploration on the routes dataset from June

In [3]:
data_routes_june.dtypes

route_code            int64
cyclenumber           int64
unlockedat           object
unlockedattime       object
lockedat             object
lockedattime         object
startstationname     object
endstationname       object
rfidnumber           object
length              float64
DurationMinutes     float64
CycleType            object
costs                 int64
Membership           object
dtype: object

In [16]:
for column in data_routes_june.columns:
    print(data_routes_june[column].value_counts())
    print()

1560103709436    2
1560245671235    2
1560186500597    2
1560270771546    2
1560098082028    2
1560017348637    2
1560104282400    2
1560019239348    2
1560180777492    2
1560340586346    2
1560100206883    2
1560105323387    2
1560275782057    2
1560058276023    2
1560097674587    1
1560248910965    1
1560087956284    1
1560312969868    1
1560023331851    1
1560326416203    1
1560030401551    1
1560095542284    1
1560070894511    1
1560101958807    1
1560163562499    1
1560252689408    1
1560172076038    1
1560195243296    1
1560093682712    1
1560096433177    1
                ..
1560083783233    1
1560010909254    1
1560191788934    1
1560173035405    1
1559985487813    1
1560163985294    1
1560189571035    1
1560167948249    1
1560172406750    1
1560254328799    1
1560329435100    1
1560174247901    1
1560025781783    1
1560157867987    1
1560089716694    1
1560010684372    1
1560251469803    1
1560230107112    1
1560153175368    1
1560138913784    1
1560082685945    1
1560198430717    1
1560260667888    1
1560019785712    1
1560138934262    1
1560076546039    1
1560248254453    1
1560098047882    1
1560345780105    1
1560229290164    1
Name: route_code, Length: 55889, dtype: int64

2337    152
2673    139
2100    139
2331    134
2448    134
2207    133
2460    132
2355    132
2518    132
2139    131
2200    130
2181    130
2336    130
2136    129
2053    129
2470    129
2160    129
2147    128
2382    128
2085    128
2279    128
2142    128
2451    128
2171    128
2204    126
2408    126
2075    126
2153    126
2400    126
2091    125
       ...
2320     19
2609     19
2613     19
2117     18
2233     18
2684     17
2060     17
2644     17
2479     17
2423     16
2218     15
2575     14
2482     13
2111     12
2166     12
2515     11
2124     10
2079     10
2564      9
2223      9
2516      8
2472      6
2741      5
2161      4
2394      4
2723      3
2411      2
2334      1
2578      1
2128      1
Name: cyclenumber, Length: 674, dtype: int64

2019-06-10    15566
2019-06-09    14033
2019-06-11    10394
2019-06-08     8124
2019-06-12     7769
2019-06-03       11
2019-06-06        6
Name: unlockedat, dtype: int64

20:28:25    7
15:04:13    7
21:50:08    7
21:17:41    7
21:13:33    7
21:37:20    7
15:57:51    7
20:58:08    6
20:14:48    6
13:40:56    6
19:46:04    6
14:09:41    6
15:08:50    6
17:44:37    6
15:58:24    6
18:38:55    6
15:27:46    6
17:40:34    6
20:59:15    6
18:19:08    6
19:27:55    6
20:40:12    6
21:13:43    6
14:49:58    6
13:23:14    6
17:25:45    6
18:14:40    6
15:48:49    6
19:04:38    6
14:58:15    6
           ..
12:00:26    1
11:51:14    1
07:25:19    1
14:10:37    1
14:16:09    1
19:10:13    1
08:51:30    1
23:00:24    1
10:54:21    1
12:24:39    1
17:20:25    1
10:06:40    1
08:24:58    1
15:33:34    1
14:53:23    1
20:45:37    1
23:54:46    1
13:18:35    1
04:50:33    1
18:08:45    1
11:17:32    1
11:29:04    1
15:00:57    1
17:58:57    1
22:22:56    1
20:21:03    1
00:32:20    1
07:47:34    1
12:47:49    1
18:49:34    1
Name: unlockedattime, Length: 36176, dtype: int64

2019-06-10    15329
2019-06-09    14461
2019-06-11    10598
2019-06-12     7804
2019-06-08     7693
2019-06-03       11
2019-06-06        6
2019-06-13        1
Name: lockedat, dtype: int64

20:19:35    8
16:42:47    7
21:44:01    7
15:47:41    7
17:57:35    7
19:33:26    7
16:21:48    7
18:06:19    7
18:56:13    7
18:18:16    6
21:42:49    6
21:27:09    6
20:22:52    6
16:33:52    6
21:03:03    6
16:49:20    6
18:27:33    6
15:18:58    6
20:39:48    6
21:12:19    6
18:24:38    6
21:26:26    6
19:17:10    6
16:34:12    6
16:21:02    6
16:33:11    6
18:04:03    6
18:53:26    6
20:01:33    6
20:51:49    6
           ..
18:56:12    1
17:34:23    1
23:09:16    1
08:21:40    1
11:29:30    1
21:44:46    1
10:54:21    1
11:46:21    1
08:10:13    1
08:17:01    1
15:33:34    1
14:55:43    1
07:12:48    1
20:45:37    1
08:51:30    1
20:28:33    1
17:45:45    1
10:06:43    1
18:08:45    1
00:23:41    1
12:43:43    1
13:47:24    1
07:44:16    1
19:45:50    1
18:33:51    1
07:17:05    1
08:19:50    1
20:09:03    1
22:10:30    1
02:28:07    1
Name: lockedattime, Length: 36132, dtype: int64

Uueturu                 2805
Soola                   1560
Eeden                   1547
Vabadussild             1431
Pirogovi plats          1399
LÃµunakeskus             1388
Turusild                1277
Annelinna kiir          1268
Annelinna keskus        1131
Anne saun               1086
Annelinn                1064
Raudteejaam             1062
Magistri                1060
Rahu                    1057
Ihaste                  1055
Roosi                   1049
Veeriku                 1025
Tarmeko                 1010
Aleksandri               965
ÃlejÃµe park              927
Kaunase puiestee         908
Vahi                     871
Aparaaditehas            869
RiiamÃ¤e                  856
Vanemuise park           844
TÃ¤htvere spordipark      831
PÃµhja puiestee           828
Raatuse kool             828
ERM                      819
Kalda tee                819
                        ...
AHHAA                    708
MÃµisavahe                688
Kannikese                687
TÃ raamatukogu           686
NÃ¤ituse                  675
Papli                    671
Postimaja                626
RÃ¤nilinn                 619
Kopli                    605
Viie tee rist            601
Tamme kool               598
Raja                     595
K. E. von Baeri          590
Tamme puiestee           581
Kivilinna                569
W. Ostwaldi              567
Annelinna gÃ¼mnaasium     556
J. Hurda                 542
Aura veekeskus           540
Kvissentali              538
Torni                    527
Kaare                    482
Tamme gÃ¼mnaasium         454
Tulbi                    452
MaarjamÃµisa              440
Sepa turg                429
Tamme staadion           380
EMÃ spordihoone          373
Lossi                    325
RÃ¼Ã¼tli                    43
Name: startstationname, Length: 68, dtype: int64

Uueturu                 2762
Soola                   1583
Eeden                   1544
Vabadussild             1441
Pirogovi plats          1433
LÃµunakeskus             1426
Annelinna kiir          1280
Turusild                1272
Annelinna keskus        1166
Ihaste                  1110
Anne saun               1085
Annelinn                1077
Rahu                    1060
Magistri                1059
Roosi                   1024
Raudteejaam             1017
Veeriku                 1012
Tarmeko                 1005
Aleksandri               983
Kaunase puiestee         924
ÃlejÃµe park              912
Aparaaditehas            879
Vahi                     872
TÃ¤htvere spordipark      857
PÃµhja puiestee           848
RiiamÃ¤e                  846
Vanemuise park           835
Raatuse kool             821
Kalda tee                821
ERM                      818
                        ...
AHHAA                    707
Kannikese                689
MÃµisavahe                679
TÃ raamatukogu           677
NÃ¤ituse                  672
Papli                    666
Postimaja                632
RÃ¤nilinn                 609
Viie tee rist            595
Tamme kool               594
Raja                     592
K. E. von Baeri          591
Kopli                    589
Tamme puiestee           580
Kivilinna                568
W. Ostwaldi              566
Annelinna gÃ¼mnaasium     548
Kvissentali              547
J. Hurda                 530
Aura veekeskus           528
Torni                    522
Kaare                    477
Tulbi                    446
Tamme gÃ¼mnaasium         442
Sepa turg                430
MaarjamÃµisa              424
Tamme staadion           376
EMÃ spordihoone          356
Lossi                    323
RÃ¼Ã¼tli                    54
Name: endstationname, Length: 68, dtype: int64

Mobile App    42660
RFID Card     13243
Name: rfidnumber, dtype: int64

0.93     225
0.90     199
0.99     186
0.81     184
0.56     179
0.61     174
0.82     173
1.02     170
0.92     168
1.70     166
0.97     165
0.91     164
0.89     164
0.84     162
1.22     160
0.83     160
0.95     159
0.79     158
1.90     158
1.59     157
0.98     156
1.30     155
1.93     155
0.94     155
0.73     154
0.76     153
1.53     153
1.84     151
1.87     151
0.67     150
        ...
10.48      1
15.50      1
17.18      1
18.61      1
20.81      1
14.29      1
12.41      1
25.40      1
21.14      1
13.27      1
22.85      1
16.79      1
10.73      1
24.74      1
16.33      1
18.17      1
12.33      1
19.34      1
27.12      1
13.24      1
15.26      1
17.90      1
11.08      1
17.11      1
19.14      1
16.27      1
15.86      1
16.02      1
14.78      1
15.00      1
Name: length, Length: 1634, dtype: int64

6.52      41
7.42      38
8.93      38
5.29      38
8.24      37
3.73      37
6.47      36
4.69      36
5.72      35
3.56      34
6.87      34
9.96      34
5.46      34
6.51      33
4.45      33
4.96      33
5.47      33
6.29      33
6.03      33
6.32      33
7.75      33
4.78      33
7.13      33
8.91      33
9.06      32
5.23      32
6.45      32
4.02      32
6.15      32
5.10      32
          ..
71.93      1
110.51     1
249.88     1
135.55     1
85.70      1
62.88      1
31.00      1
60.63      1
71.18      1
147.89     1
82.54      1
48.82      1
116.20     1
40.57      1
172.85     1
45.41      1
42.79      1
64.16      1
193.71     1
54.95      1
71.14      1
147.95     1
122.88     1
111.58     1
141.84     1
87.34      1
168.73     1
46.82      1
69.21      1
76.34      1
Name: DurationMinutes, Length: 7142, dtype: int64

Pedelec    42076
Bike       13827
Name: CycleType, dtype: int64

0    54468
1     1099
2      214
3       69
4       53
Name: costs, dtype: int64

3-Month Free Membership            35973
1-month Free Membership            10520
Free Membership (with bus card)     9401
1 Year Membership                      9
Name: Membership, dtype: int64

In [5]:
# Missing values in the datasets are defined as '-- MÃ¤Ã¤ramata --' and 'Undetermined'
def missing_values(data):
    total_rows = len(data.index)
    for column in data.columns:
        total_missing = 0
        if type(data[column].loc[0]) == str:
            total_missing += data[column].str.contains('-- MÃ¤Ã¤ramata --').sum()
            total_missing += data[column].str.contains('Undetermined').sum()
        if total_missing > 0:
            print ('Number of missing values in column \'' + column + '\': ' + str(total_missing) )

In [6]:
print("JUNE:")
missing_values(data_routes_june)
print("JULY:")
missing_values(data_routes_july)
print("AUGUST:")
missing_values(data_routes_august)
print("SEPTEMBER:")
missing_values(data_routes_september)

JUNE:
Number of missing values in column 'startstationname': 400
Number of missing values in column 'endstationname': 254
JULY:
Number of missing values in column 'startstationname': 306
Number of missing values in column 'endstationname': 261
AUGUST:
Number of missing values in column 'startstationname': 495
Number of missing values in column 'endstationname': 539
SEPTEMBER:
Number of missing values in column 'startstationname': 490
Number of missing values in column 'endstationname': 628

## Data cleaning
### 1. Removing rows with missing and incorrect values in columns 'startstationname' and 'endstationname'

In [7]:
def remove_missing_rows(data):
    # Missing values in the datasets are defined as '-- MÃ¤Ã¤ramata --' and 'Undetermined'
    indices = data[(data['startstationname'] == '-- MÃ¤Ã¤ramata --')].index
    data.drop(indices, inplace=True)
    indices = data[(data['startstationname'] == 'Undetermined')].index
    data.drop(indices, inplace=True)
    indices = data[(data['endstationname'] == '-- MÃ¤Ã¤ramata --')].index
    data.drop(indices, inplace=True)
    indices = data[(data['endstationname'] == 'Undetermined')].index
    data.drop(indices, inplace=True)
    
    # Stations 'Warehouse', 'TÃ¶Ã¶koda' and 'Delta' are not publically usable
    indices = data[(data['startstationname'] == 'Warehouse')].index
    data.drop(indices, inplace=True)
    indices = data[(data['endstationname'] == 'Warehouse')].index
    data.drop(indices, inplace=True)
    indices = data[(data['startstationname'] == 'Delta')].index
    data.drop(indices, inplace=True)
    indices = data[(data['endstationname'] == 'Delta')].index
    data.drop(indices, inplace=True)
    indices = data[(data['startstationname'] == 'TÃ¶Ã¶koda')].index
    data.drop(indices, inplace=True)
    indices = data[(data['endstationname'] == 'TÃ¶Ã¶koda')].index
    data.drop(indices, inplace=True)

In [8]:
remove_missing_rows(data_routes_june)
remove_missing_rows(data_routes_july)
remove_missing_rows(data_routes_august)
remove_missing_rows(data_routes_september)

### 2. Removing rides that are less than 100 m.
These are the 'rides' where the bike is undocked and then re-docked right away.

In [9]:
def remove_less_than_100m_rides(data):
    indices = data[(data['length'] < 0.100)].index
    data.drop(indices, inplace=True)

In [10]:
remove_less_than_100m_rides(data_routes_june)
remove_less_than_100m_rides(data_routes_july)
remove_less_than_100m_rides(data_routes_august)
remove_less_than_100m_rides(data_routes_september)

### 3. Correcting spelling differences in Membership column

In [11]:
data_routes_june.Membership.value_counts()

3 month free membership            20049
3-Month Free Membership            15924
Free Membership (with bus card)     9401
1 month free membership             7555
1-month Free Membership             2965
1 Year Membership                      5
1 YEAR MEMBERSHIP                      4
1 mo                                   1
Name: Membership, dtype: int64

In [12]:
def correct_spelling(data):
    data.Membership = data.Membership.replace(to_replace ="3 month free membership", value = "3-Month Free Membership")
    data.Membership = data.Membership.replace(to_replace ="1 DAY MEMBERSHIP", value = "1 Day Membership")
    data.Membership = data.Membership.replace(to_replace ="1 YEAR MEMBERSHIP", value = "1 Year Membership")
    data.Membership = data.Membership.replace(to_replace ="1 WEEK MEMBERSHIP", value = "1 Week Membership")
    data.Membership = data.Membership.replace(to_replace ="1 month free membership", value = "1-month Free Membership")
    data.drop(data[(data.Membership == 'Free M')].index, inplace=True)
    data.drop(data[(data.Membership == '1 mo')].index, inplace=True)

In [13]:
correct_spelling(data_routes_june)
correct_spelling(data_routes_july)
correct_spelling(data_routes_august)
correct_spelling(data_routes_september)

In [14]:
data_routes_june.Membership.value_counts()

3-Month Free Membership            35973
1-month Free Membership            10520
Free Membership (with bus card)     9401
1 Year Membership                      9
Name: Membership, dtype: int64

### 4. Exporting cleaned datasets to csv

In [15]:
data_routes_june.to_csv(path_or_buf="Cleaned data\\routes_2019_06_clean.csv",index=False)
data_routes_july.to_csv(path_or_buf="Cleaned data\\routes_2019_07_clean.csv",index=False)
data_routes_august.to_csv(path_or_buf="Cleaned data\\routes_2019_08_clean.csv",index=False)
data_routes_september.to_csv(path_or_buf="Cleaned data\\routes_2019_09_clean.csv",index=False)